### PR TITLE
auto grid for wstep

### LINKED ISSUE #456: Bad resolution for low pressure spectra
At ~ 0.001 mbar  the current spectral grid doesn't resolve the spectra properly

image

The new `wstep='auto'` feature introduced in RADIS this year should fix that

### PR DESCRIPTION
**Pull request by erwanp**
Should fix #456  , make computations faster at high pressure , and ensure high accuracy at low pressure

Uses the auto-wstep feature of @anandxkumar

### CODE REVIEW

**Comment by suzil** [comment]
@erwanp There's a backend error from this change. I just reverted the commit until we figure out the problem. This is the error from calling the backend:
```py
Traceback (most recent call last):
  File "/var/task/app.py", line 23, in lambda_handler
    spectrum = radis.calc_spectrum(
  File "/var/task/radis/lbl/calc.py", line 398, in calc_spectrum
    _calc_spectrum(
  File "/var/task/radis/lbl/calc.py", line 522, in _calc_spectrum
    sf = SpectrumFactory(
  File "/var/task/radis/lbl/factory.py", line 418, in __init__
    wavenumber, wavenumber_calc = _generate_wavenumber_range(
  File "/var/task/radis/lbl/factory.py", line 1735, in _generate_wavenumber_range
    wavenumber = arange(wavenum_min, wavenum_max + wstep, wstep)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
```
It wasn't obvious to me what the problem is. Do you maybe know what it is?

**Comment by erwanp** [comment]
I've never add this. @anandxkumar did you encounter it while working on wstep auto ?

**Comment by anandxkumar** [comment]
@erwanp didn't encounter this error before. My guess would be in the `_generate_wavenumber_range` function, the `wstep` is still `'auto'` during ` wavenumber = arange(wavenum_min, wavenum_max + wstep, wstep)` which leads to the error.
@suzil can you share the parameters that raised the error, so that it can be reproduced?

**Comment by erwanp** [comment]
I tested the code snippet public 0.10.3 version on [radis-Lab](https://radis.github.io/radis-lab/) and it worked. 

However, I think I found the culprit : radis on radis-app still runs version 0.9.28: https://github.com/suzil/radis-app/blob/master/lib/radis-lambda/requirements.txt

**Pull request merged**
